const LIST_PRODUCT = "LIST_PRODUCT";
const GET_PRODUCT = "GET_PRODUCT";
const LIST_PRODUCT_CATEGORIES = "LIST_PRODUCT_CATEGORIES";
const LIST_PRODUCT_BY_CATEGORY = "LIST_PRODUCT_BY_CATEGORY";
const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
const PAGINATE_PRODUCTS = "PAGINATE_PRODUCTS";
export {
  LIST_PRODUCT,
  GET_PRODUCT,
  LIST_PRODUCT_CATEGORIES,
  LIST_PRODUCT_BY_CATEGORY,
  SEARCH_PRODUCTS,
  PAGINATE_PRODUCTS,
};
